language: node_js

node_js:
  - "node"
  - "lts/*"

cache:
  directories:
    - "node_modules"

script: echo "Running tests against $(node -v)..." && yarn test

jobs:
  include:
    - stage: Build
      script: yarn build
    - stage: Lint
      script: yarn lint
